### ISSUE TITLE
@linq fails when function name is preceded by module name

### ISSUE THREAD

**Issue by bkamins** [JuliaStats/DataFramesMeta.jl#102]
Here is a MWE of the problem (run under Julia 1.0, but I guess the problem was also earlier):

```
julia> using DataFrames, DataFramesMeta, Statistics
julia> df = DataFrame(x=1)
1×1 DataFrame
│ Row │ x │
├─────┼───┤
│ 1   │ 1 │

julia> @where(df, :x .== Statistics.mean(:x))
1×1 DataFrame
│ Row │ x │
├─────┼───┤
│ 1   │ 1 │

julia> @linq df |> @where(:x .== Statistics.mean(:x))
ERROR: LoadError: MethodError: Cannot `convert` an object of type Expr to an object of type DataFramesMeta.SymbolParameter
```

**Comment by pdeffebach** [comment]
I'm trying to figure this out so I can contribute more to this package. It's from the recursive `replacefuns` function here: 

https://github.com/JuliaStats/DataFramesMeta.jl/blob/5d0b9b13d0755badbc82279a3acf02e99dba7330/src/linqmacro.jl#L80

Parametric constructors accept types, numbers, functions, and symbols... but not expressions. There is probably a `gensym` or anonymous function here that would do the trick.

**Comment by bkamins** [comment]
A funny thing is that it seems that I have fixed this bug 3 months ago (I have thought I have fixed if for another case but the fix solves this). Use: `] add DataFramesMeta#master` and the code will work.

The problem is that `DataFramesMeta` has not been released for a very long time. We should focus on upgrading it to Julia 1.0 (I will push a PR fixing this today) and all will work.
