### ISSUE TITLE
@where on a grouped dataframe throws an error

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/DataFramesMeta.jl#109]
```
julia> ans = @linq df |>
       groupby(:a) |>
       where(:b .== maximum(:b))
ERROR: MethodError: Cannot `convert` an object of type BitArray{1} to an object of type Bool
Closest candidates are:
  convert(::Type{T<:Number}, ::T<:Number) where T<:Number at number.jl:6
  convert(::Type{T<:Number}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T<:Integer}, ::Ptr) where T<:Integer at pointer.jl:23
  ...
Stacktrace:
 [1] setindex!(::Array{Bool,1}, ::BitArray{1}, ::Int64) at ./array.jl:769
 [2] where(::GroupedDataFrame, ::getfield(Main, Symbol("##3#4"))) at /Users/peterdeffebach/.julia/packages/DataFramesMeta/oLnYB/src/DataFramesMeta.jl:192
 [3] top-level scope at none:0
```

This is in reference to [this](https://discourse.julialang.org/t/simplifying-this-dataframe-aggregation-operation/14648/15) discourse thread. 

when evaluating functions, `@where(g::GroupedDataFrame, args...)` should `@where` behave like a grouped transform? 

The alternative is to add one more line: 

```
julia> ans = @linq df |>
       groupby(:a) |>
       transform(m = maximum(:b) |>
       where(:b .== maximum(:m))
```

EDIT: I orginally included an example where I thought `R` had the behavior I expected. This was wrong, R has the same behavior -- indexing groups -- as DataFramesMeta does now. I thought this was more of an R gotcha than it was.

**Comment by tshort** [comment]
Right now, `@where` filters on groups. `@orderby` works the same. You can do things like:

```jula
@where(gd, :mean(:a) < 4)
```
That means that groups are filtered out that don't meet the criteria given. 

Your request seems like a different feature. Maybe that operation needs a different name, or we need a better way to indicate operations inside a subgroup.

**Comment by pdeffebach** [comment]
Thanks for the reply. 

It's tough to say. I would bet that my desired behavior is a bit of an edge case. Given that boolean vectors are very cheap, this seems reasonable: 

```
julia> ans = @linq df |>
       groupby(:a) |>
       transform(highest = :b .== maximum(:b) |>
       where(:highest)
```

The behavior of `@where` makes sense if you are coming from `dplyr`, so I think it's fine.
