### ISSUE TITLE
Macro Conflict with Lazy.jl

### ISSUE THREAD

**Issue by toddleo** [JuliaStats/DataFramesMeta.jl#12]
I'm trying to reproduce the examples on READEME.jl, however, I found that if the `using Lazy` statement is executed before `using DataArrays, DataFrames, DataFramesMeta`, an error will be raised when calling `@where(df, :x .> 1)`: **ERROR: wrong number of arguments**

I am using Julia v0.4, on Ubuntu 14.04 x64 desktop version.

**Comment by tshort** [comment]
Thanks for the report. Both DataFramesMeta and Lazy define an `@with` macro. That's one downside of macros relative to methods -- it's much more common for problems to occur from namespace clashes. 

It's likely a scope problem on one side or the other (probably in DataFramesMeta). I'm cc'ing @one-more-minute, so he's aware of the issue, too.

**Comment by tshort** [comment]
This looks like a problem with how I misused `esc`.

**Comment by tshort** [comment]
I just pushed a fix. This version isn't in METADATA yet, so you'll have to checkout master to try it. If there's still problems, please reopen this issue.

**Comment by sethchandler** [comment]
So I am experiencing this problem too.  How can I avoid the problem.

**Comment by tshort** [comment]
Does it happen with the latest?

`Pkg.checkout("DataFramesMeta")`

**Comment by sethchandler** [comment]
Yes.  Here’s my notebook showing the problem.  By the way, although I am very experienced with Mathematica and decent with R, I am very new (but excited) to Julia, so if I am doing something stupid, it would not surprise me.

**Comment by tshort** [comment]
Attachments don't work. Can you paste the text?

**Comment by sethchandler** [comment]
Here’s the JSON stuff from the ipynb file

{
 "metadata": {
  "language": "Julia",
  "name": "",
  "signature": "sha256:7e0714ff1bf1b8aa6c16145e581bbc7b5bd8a69d957ccdfb3d17be512a62d423"
 },
 "nbformat": 3,
 "nbformat_minor": 0,
 "worksheets": [
  {
   "cells": [
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "Pkg.checkout(\"DataFramesMeta\")"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stderr",
       "text": [
        "INFO: Checking out DataFramesMeta master...\n"
       ]
      },
      {
       "output_type": "stream",
       "stream": "stderr",
       "text": [
        "INFO: Pulling DataFramesMeta latest master...\n"
       ]
      },
      {
       "output_type": "stream",
       "stream": "stderr",
       "text": [
        "INFO: No packages to install, update or remove\n"
       ]
      }
     ],
     "prompt_number": 1
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "using Lazy, DataFrames"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 2
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "df = DataFrame(x = 1:3, y = [2, 1, 2])"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "html": [
        "<table class=\"data-frame\"><tr><th></th><th>x</th><th>y</th></tr><tr><th>1</th><td>1</td><td>2</td></tr><tr><th>2</th><td>2</td><td>1</td></tr><tr><th>3</th><td>3</td><td>2</td></tr></table>"
       ],
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 3,
       "text": [
        "3x2 DataFrame\n",
        "| Row | x | y |\n",
        "|-----|---|---|\n",
        "| 1   | 1 | 2 |\n",
        "| 2   | 2 | 1 |\n",
        "| 3   | 3 | 2 |"
       ]
      }
     ],
     "prompt_number": 3
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "@with(df, :y + 1)"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "ename": "LoadError",
       "evalue": "wrong number of arguments\nwhile loading In[4], in expression starting on line 1",
       "output_type": "pyerr",
       "traceback": [
        "wrong number of arguments\nwhile loading In[4], in expression starting on line 1",
        ""
       ]
      }
     ],
     "prompt_number": 4
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 5
    }
   ],
   "metadata": {}
  }
 ]
}




And here are the input cells

Pkg.checkout("DataFramesMeta”)

using Lazy, DataFrames

df = DataFrame(x = 1:3, y = [2, 1, 2])

@with(df, :y + 1)

**Comment by tshort** [comment]
I'm not at a computer where I can check it, but try `DataFramesMeta.@with(df, :y + 1)`.

Or, just don't load Lazy.

**Comment by floswald** [comment]
I have the same problem as the OP. I guess the issue should be reopened?

**Comment by floswald** [comment]
@tshort do you recommend using `@linq` instead of the functions in `Lazy`? that seems to do exactly the  same things. It would be good to know if you plan on keeping the `@linq` around or not.

**Comment by tshort** [comment]
Yes, for now, I recommend using `@linq`. I should just remove the `Lazy` example from the README.
