### ISSUE TITLE
where() takes only one expression

### ISSUE THREAD

**Issue by toddleo** [JuliaStats/DataFramesMeta.jl#13]
Suppose I want to filter my dataframe by multiple constrains (which is not rare):

    @where(df, :x1 .== 5, :x2 .== 3)

but now it gives back: **ERROR: wrong number of arguments**. Can it be enhanced to take multiple constrains as how dplyr in R does? :D

**Comment by tshort** [comment]
It could probably be enhanced, the easiest way to do that now is:

```julia
@where(df, :x1 .== 5 & :x2 .== 3)
```
I assume dplyr uses `&` for this, but I guess `|` could be a reasonable use, too.

**Comment by garborg** [comment]
It needs a couple extra parens, because of the high precedence of `|` and `&` in Julia:
```julia
@where(df, (:x1 .== 5) & (:x2 .== 3))
```

Precedence the operators may be lowered in the future: JuliaLang/julia#5187

**Comment by tshort** [comment]
You're right! Great point, Sean. That's a good reason to implement extra
arguments for multiple constraints. Given that it's a macro, we might also
be able to find syntax that doesn't require extra parens (although that
might be trying to do too magic with macros).

**Comment by nalimilan** [comment]
What's the point of supporting several expressions? Just to avoid adding the extra parentheses? I'd rather lobby for changing operator precedence, which is annoying anyway (as evidence of this, among others, [this recent julia-users thread](https://groups.google.com/d/msg/julia-users/bGeL70sZEoI/UBCxLQgBLeMJ)).
