### ISSUE TITLE
Rebinding external vars inside of `@with`

### ISSUE THREAD

**Issue by davidagold** [JuliaStats/DataFramesMeta.jl#15]
EDIT: Nevermind, this turns out not really to be an issue. See comment below. I'm leaving the following original post unedited for posterity.

This issue arises while trying to rebind an external variable inside of an `@with` call:
```
julia> using DataFrames, DataFramesMeta

julia> df = DataFrame(A = 1:3, B = [2, 1, 2])
3x2 DataFrame
| Row | A | B |
|-----|---|---|
| 1   | 1 | 2 |
| 2   | 2 | 1 |
| 3   | 3 | 2 |

julia> y = 1
1

julia> @with df for i in 1:3; :A[i] += y end

julia> df
3x2 DataFrame
| Row | A | B |
|-----|---|---|
| 1   | 2 | 2 |
| 2   | 3 | 1 |
| 3   | 4 | 2 |

julia> @with df for i in 1:3; y += :A[i] end
ERROR: y not defined
 in ##24126 at /Users/David/.julia/v0.3/DataFramesMeta/src/DataFramesMeta.jl:1

julia> @with df y += :A[1]
ERROR: y not defined
 in ##24128 at /Users/David/.julia/v0.3/DataFramesMeta/src/DataFramesMeta.jl:47
```
I can't remember the particular feature of Julia's scoping logic that provides this behavior. It seems that inside of a local scope, an external variable can be referenced so long as it is not rebound.

Of course, defining a function through which to pass the external value works fine:
```
julia> function f(x) @with df x += :A[1] end
f (generic function with 2 methods)

julia> f(y)
6
```
However, in the interest of making certain kinds of functionality more generally accessible in the REPL (think demographics of users who aren't used to wrapping things in functions), I wonder if we should provide some sort of tool (macro) for doing this more efficiently. Something like
```julia
@relay y @with df y += :A[1]
```
where `@relay` would generate a function, replace all instances of `y` in the body `@with df y += :A[1]` with a variable, and then call that function on `y`. Incorporating functionality for multiple external variables might be tricky, though at this point of playing around I believe an efficient solution is possible. I'm happy to work on such a feature. 

I don't know if this proposal approaches the realm of too much magic, but the core idea seems pretty straightforward. I would also provide thorough documentation on the internals, so lay users would be able to troubleshoot more effectively and understand their code better in general. 

Or, we could just tell folks to wrap their code in a function.

**Comment by davidagold** [comment]
As mentioned above, this turns out not actually to be an issue, but rather just Julia's scope logic. Note that even writing (as above)
```
julia> function f(x) @with df x += :A[1] end
f (generic function with 2 methods)

julia> f(y)
6
```
won't actually change the value of the global variable `y`; it simply won't result in an undefined variable error. In order actually to reassign the global variable `y` one must write `y = f(y)`. This issue has two faces, which I've more or less conflated above. The first is, to which names does an inner scope have access? The second is, in which scope must one refer to a variable in order to reassign it? If I have this straight, the only scope in which a variable can be reassigned is the scope in which it is initially assigned. Thus, even if one writes 
```julia
function f(x)
    x += 1
end
```
subsequently writing `f(y)` will not change the binding of `y`. However, one can refer to a name in an enveloping scope, so long as one does not attempt to reassign it. 

I know, this is rather beginner stuff. So, please humor my having filed an issue about it above.

**Comment by arnaudmgh** [comment]
Hello @davidagold, it might be an issue of mutable vs immutable types. Your call `f(y)` will not change y in any case because y is immutable. `y = 1` creates an Integer, which is immutable, hence the function `f` cannot change it. However if y is mutable, for instance if it is an Array, then f can change it's content. See for instance: 

    df = DataFrame(A = 1:3, B = [2, 1, 2])
    y = [1, 2]
    function f(x) @with df x[1] += :A[1] end
    f(y), y # (2,[2,2])
    f(y), y # (3,[3,2])
