### ISSUE TITLE
@based_on not working?

### ISSUE THREAD

**Issue by bramtayl** [JuliaStats/DataFramesMeta.jl#17]
It seems as if DataFrames.based_on has been depreciated? I'm very very new to Julia, so I might just be confused. The error message I get is based_on is not defined. Here is an example:

    using RDatasets
    iris = dataset("datasets", "iris")

    @as _ begin
      iris
      groupby(_, :Species)
      @based_on(_, Mean_Petal_Length = mean(:Petal_Length))
    end

**Comment by davidagold** [comment]
@bramtayl Have you made sure that you're using the DataFramesMeta package as well as the DataFrames package? `@based_on lives in the former. Perhaps a little confusing. You can add the former package by calling `Pkg.add("DataFramesMeta")`.

**Comment by bramtayl** [comment]
Yes. I checked the sourced for DataFramesMeta.@based_on, below.

    macro based_on(x, args...)
      esc(:( DataFrames.based_on($x, _DF -> DataFramesMeta.@with(_DF, DataFrames.DataFrame($(args...)))) ))
    end

However, it looks like DataFrames.based_on has been depreciated as of 0.5.2:

> Removes expression-based indexing, including `with`, `within!`, `based_on`, etc.

**Comment by davidagold** [comment]
Ah, I totally misunderstood your question! I apologize. Are you looking for a way to produce something like:
```
3x2 DataFrame
| Row | Species      | mean_petal_length |
|-----|--------------|-------------------|
| 1   | "setosa"     | 1.462             |
| 2   | "versicolor" | 4.26              |
| 3   | "virginica"  | 5.552             |
```
?

**Comment by bramtayl** [comment]
Yes, and since I've written my post I've realized this can by done with @by.

**Comment by davidagold** [comment]
Indeed. Glad to hear. (Also, it's good to wrap macro names in \` s so as not to tag users with the same username as the macro name.)
