### ISSUE TITLE
dplyr n() equivalent

### ISSUE THREAD

**Issue by bramtayl** [JuliaStats/DataFramesMeta.jl#18]
dplyr provides n() which gives the number of rows in a subgroup. In Julia, it would look something like this:

    iris2 = @> begin
      iris
      @by( :Species, 
          count = n(),
          sepal_length = mean(:SepalLength))
    end

In order to get what I want, I have to do this:

    iris2 = @as _ begin
        iris
        @transform(count = 1)
        @by( :Species,
            count = sum(:count),
            sepal_length = mean(:SepalLength))
    end

**Comment by arnaudmgh** [comment]
I also use a lot these dplyr functions a lot, and I came up with that for Julia:
R: group_by(df, node, replicate) %>% summarize(n=n())
Julia: by(df, [:node, :replicate], x -> size(x, 1))
Best, 

Arnaud

**Comment by bramtayl** [comment]
can that be done within the context of @by and chaining?

**Comment by arnaudmgh** [comment]
I guess you could use the function length instead of mean in your example
to get the same output as n()

**Comment by bramtayl** [comment]
You mean like this? Because that doesn't give me the desired output.

    iris2 = @as _ begin
        iris
        @transform(_, count = 1)
        @by(_, :Species,
            count = length(_),
            sepal_length = mean(:SepalLength))
    end

**Comment by arnaudmgh** [comment]
length(:SepalLength)

**Comment by mmagnuski** [comment]
Just to reiterate, the solution is to:
```julia
@by(df, :Species, 
        mean_sepal_length = mean(:SepalLength),
        count = length(:SepalLength))
```
can this be closed?
