### ISSUE TITLE
Publish new version to METADATA?

### ISSUE THREAD

**Issue by emilbayes** [JuliaStats/DataFramesMeta.jl#20]
`@byrow` doesn't seem to be included in the version installed using `Pkg.add`

**Comment by tshort** [comment]
Just a heads up--I'm out for a couple of weeks and won't be able to take care of this.

**Comment by emilbayes** [comment]
Should I file an issue over there instead, or attempt at PR at the METADATA.jl repo?

**Comment by tshort** [comment]
You could do a PR at the metadata repo.

**Comment by lbollar** [comment]
I just tried to use by @byrow using latest julia build and DataFramesMeta installed using Pkg.clone for latest version here. get an undefvarerror

```
Julia Version 0.4.0-pre+7316
Commit 86a2a31 (2015-09-05 20:44 UTC)

@test @byrow!(df, if :A > :B; :A = 0 end) == DataFrame(A = [1, 0, 0], B = [2, 1, 2])
ERROR: UndefVarError: @byrow! not defined
```

I'm a newb and was trying to get involved. Tried to see if there was a way for me to fix this, but I don't have enough knowledge for this.

**Comment by tshort** [comment]
Release tagged and published...
