### ISSUE TITLE
regression with `@byrow`

### ISSUE THREAD

**Issue by ssfrr** [JuliaStats/DataFramesMeta.jl#24]
On current master
```
myd = DataFrame(x=zeros(10), y=ones(10))
@byrow myd begin
    println(:x)
end
```
gives me the error "ERROR: myd not defined"

On commit e84ac6c it works as expected.

**Comment by bramtayl** [comment]
My update changed `@byrow` to `@byrow!` . Dunno if that's part of the problem

**Comment by ssfrr** [comment]
Hm, not sure. Working now with #29 locally though.
