### ISSUE TITLE
@where: wrong number of arguments

### ISSUE THREAD

**Issue by bigpas** [JuliaStats/DataFramesMeta.jl#37]
Hi, 

why?

```
@where((df, :x .> x) & (df, :y .== 3))
ERROR: wrong number of arguments
```

NB: 
```
df = DataFrame(x = 1:3, y = [2, 1, 2])
x = [2, 1, 0]

```

p.s. 
```
versioninfo()
Julia Version 0.4.1
Commit cbe1bee (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by nalimilan** [comment]
Why do you repeat `df`? `@where df :x .> x & :y .== 3` is enough.

(In the future, please use the julia-stats mailing list for questions, and keep GitHub for bug reports.)

**Comment by bigpas** [comment]
Hi,

thanks.
I was just following the documentation.

best,

**Comment by nalimilan** [comment]
Could you give a link to that incorrect documentation? Thanks!

**Comment by bigpas** [comment]
No problem.

https://github.com/JuliaStats/DataFramesMeta.jl

it says:
`@where(df, :x .> x, :y .== 3) # the two expressions are "and-ed"`

please, let me know if I did something wrong.
This is my first contact with "DataFramesMeta" but it sounds like a super
cool project.


best,

**Comment by nalimilan** [comment]
Ah, good catch, thanks! Looks like this syntax doesn't work anymore. Not sure whether the docs should be changed or the code fixed, but @tshort will tell.

**Comment by tshort** [comment]
That feature was just added, and I haven't tagged a new version. To try it out, you can try the development version with `Pkg.checkout("DataFramesMeta")`. I'll try to tag a new version over the weekend. There are still a couple of cleanups needed.

Please reopen if needed.

**Comment by nalimilan** [comment]
@tshort Just being curious, but why did you feel the need for this? Does it make anything possible that previously wasn't? Otherwise, using `&` sounds much clearer to me, as is illustrated by the fact that you had to introduce a comment in README.md explaining what `@where(df, :x .> x, :y .== 3)` does.

**Comment by tshort** [comment]
See #13 for background. My biggest reason is precedence of `&`. `@where(df, :x .> x & :y .== 2)` doesn't work right. You need `@where(df, (:x .> x) & (:y .== 2))`. So, `@where(df, :x .> x, :y .== 2)` is simpler.

**Comment by nalimilan** [comment]
Funny, I didn't remember I had already commented on that issue. Well, I've not changed my mind! :-)
