### ISSUE TITLE
Error using function chaining and Lazy.lj

### ISSUE THREAD

**Issue by tcovert** [JuliaStats/DataFramesMeta.jl#40]
When I try to do something very similar to the Lazy.jl example in the docs, I get a error informing me that both Lazy.jl and DataFramesMeta.jl have macros called "with", and as a result, uses of with must be "qualified".  Here is the code block I am trying to run.  For reference, "ndic" is a dataframe, and dfsplit() is a helper function that more or less calls split() in a particular way.

using DataFrames
using Lazy
using DataFramesMeta

...

pools = @> begin
    ndic
    @where(!isna(:ProducedPools))
    @by(:FileNo, df -> dfsplit(df, :ProducedPools, ','))
    @select(:FileNo, poolorder = :splitorder, pool = :splitval)
    @where(:pool .!= "Confidential")
end

Here is the error I get:

julia> include("CODE.jl")
WARNING: both DataFramesMeta and Lazy export "@with"; uses of it in module Main must be qualified
ERROR: LoadError: UndefVarError: @with not defined
 in include at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
while loading /PATH_TO_CODE/CODE.jl, in expression starting on line 36

**Comment by tshort** [comment]
It's probably possible to get rid of the error but not the warning. I think replacing uses of `@with` with `DataFramesMeta.@with` in the code should do that. I won't have time until late next week, so if anyone wants it before that, please make a pull request.

If that doesn't work, we should remove those docs or pull in the code for the `@>` macro from Lazy.

**Comment by tshort** [comment]
Should be fixed by #41. I added tests that include `@>` and `@as`. It won't show up in the release version until I tag it, so you'll have to clone it to use it before that.
