### ISSUE TITLE
transform() vs select()

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/DataFramesMeta.jl#45]
I wonder what's the fundamental difference between `transform` and `select`. The most visible difference seems to be that the former always returns as many rows as the input, contrary to `select`:
```julia
julia> df = DataFrame(A=1:3)
3x1 DataFrames.DataFrame
│ Row │ A │
┝━━━━━┿━━━┥
│ 1   │ 1 │
│ 2   │ 2 │
│ 3   │ 3 │

julia> @select(df, A=1)
1x1 DataFrames.DataFrame
│ Row │ A │
┝━━━━━┿━━━┥
│ 1   │ 1 │

julia> @transform(df, A=1)
3x1 DataFrames.DataFrame
│ Row │ A │
┝━━━━━┿━━━┥
│ 1   │ 1 │
│ 2   │ 1 │
│ 3   │ 1 │
```

Are there any other differences? The documentation isn't very explicit about them.

Do we really need two different macros here? I find it a bit confusing, and the names don't really reflect the differences between them. AFAICT, dplyr only offers `select` and `mutate` (equivalent of `transform`) because the former only allows selecting columns, and not transforming them. It sounds like a powerful SQL-like `@select` (what we have now) is a better solution.

**Comment by nalimilan** [comment]
By the same line of thinking, I would remove `@ix` and only keep `@where`. Chaining should be the recommended way of combining `@select` and `@where`. This would make the API quite clearer.

**Comment by tshort** [comment]
The main difference between `@select` and `@transform` is that the result of `@select` only includes columns indicated, and `@transform` includes all of the original columns plus any new columns created. Both are useful. The docs could use improvement.

As you've noted, the `@select(df, A=1)` is likely a bug. It should probably recycle (although this is a bit of a corner case).

I agree that it might help to remove `@ix`.

**Comment by nalimilan** [comment]
Indeed, makes sense. I wonder whether `@transform` should be called `@selectall` (by analogy with `SELECT * FROM`), to make it obvious that semantics are otherwise the same as `@select`.

**Comment by tshort** [comment]
I added a couple of notes to the README. If that's not good enough, please reopen.

**Comment by nalimilan** [comment]
I can't find them, I guess you forgot to call `git push`. :-)
