### ISSUE TITLE
Cannot use transform to square the values of a column

### ISSUE THREAD

**Issue by bsouthwood** [JuliaStats/DataFramesMeta.jl#53]
Hello I have a float column in my DataFrame and I can't use "*" to multiply 2 columns together. I can however use "+".

leg[:gi]
 DataArrays.DataArray{Float64,1}:

This fails.

leg = @transform(leg, gi_sq = :gi * :gi)
MethodError: `*` has no method matching *(::Array{Float64,1}, ::Array{Float64,1})

This works

leg = @transform(leg, gi_sq = :gi + :gi)

**Comment by tshort** [comment]
I'm not at a computer to double-check, but I think you want elementwise multiplication (`.*`) rather than `*`.

Also, please quote your code that uses macros, otherwise the GitHub user named `@transform` will be bothered.

**Comment by ellisvalentiner** [comment]
using Datasets
    iris = datasets("datasets", "iris")
    @transform(iris, sepal_length_sq = :SepalLength .* :SepalLength)

works fine. I suggest closing this issue.
