### ISSUE TITLE
@newcol in @byrow! not defined

### ISSUE THREAD

**Issue by dun10p** [JuliaStats/DataFramesMeta.jl#54]
Hi. Sorry to be a bother. I'm getting an error saying "UndefVarError @newcol not defined", when running the block in the readme that includes @byrow! and @newcol as displayed below.

    df = DataFrame(A = 1:3, B = [2, 1, 2])
    df2 = @byrow! df begin
        @newcol colX::Array{Float64}
        @newcol colY::DataArray{Int}
        :colX = :B == 2 ? pi * :A : :B
         if :A > 1 
            :colY = :A * :B
        end
    end

I'm trying to apply this to my own dataframe to bring separate time and date columns into a single column that contains DateTime elements. I was thinking this would work:    

dateForm = Dates.DateFormat("d-u-y H")
newMachineData = @byrow! MachineData begin
    @newcol DT::Array{DateTime}
    :DT = DateTime(string(:DATE, " ", :HOUR), dateForm)
end

However, the error with @newcol is raised. It's likely I'm missing something simple though. I am new to Julia

**Comment by tshort** [comment]
It may be that the readme is ahead of the released version of
DataFramesMeta. You may have to checkout the most recent commit to get this
feature. I'm not at a location I can check easily.


---------- Forwarded message ----------

**Comment by nalimilan** [comment]
Yes, last version was in December, and these functions are newer than that AFAIK. It's indeed always confusing that you get the development version of the README when you browser a GitHub project. In the long-term, I guess documentation should move to Documenter.jl anyway.

**Comment by dun10p** [comment]
Thank  you guys! I apologize for the mistake.
