### ISSUE TITLE
Inexact

### ISSUE THREAD

**Issue by alexhallam** [JuliaStats/DataFramesMeta.jl#66]
I seem to be getting an error and wanted to see if I was using `DataFramesMeta` incorrectly. Here is the set-up

```julia
julia> a
12-element Array{Float64,1}:
  3.1
  6.8
  9.0
  9.0
 11.3
 16.2
  8.7
  9.0
 10.1
 12.1
 18.7
 23.1

julia> b
12-element Array{Int64,1}:
 0
 1
 0
 0
 1
 0
 0
 0
 1
 1
 0
 1
```

I wanted to filter by the rows, `a`, that were unique. This would result in the following

```julia
julia> unique(df[:a])
10-element DataArrays.DataArray{Float64,1}:
  3.1
  6.8
  9.0
 11.3
 16.2
  8.7
 10.1
 12.1
 18.7
 23.1
```

It seemed that `@where` would be appropriate, but I got an `InexactError()`.

```julia
julia> @where(df, unique(df[:a]))
ERROR: InexactError()
 in copy!(::Base.LinearFast, ::Array{Int64,1}, ::Base.LinearFast, ::Array{Float64,1}) at ./abstractarray.jl:559
 in getindex(::DataFrames.DataFrame, ::DataArrays.DataArray{Float64,1}) at /Users/alexhallam/.julia/v0.5/DataFrames/src/dataframe/dataframe.jl:234
 in where(::DataFrames.DataFrame, ::##34#35) at /Users/alexhallam/.julia/v0.5/DataFramesMeta/src/DataFramesMeta.jl:164
```

How can I `filter` -- in the dplyr sense of the word -- by the unique values in `a`.

**Comment by nalimilan** [comment]
This command woudn't work in dplyr either. Try with the poorly-named `@where(df, !nonunique(df[:a]))`, or just `unique(df, :a)`.

**Comment by alexhallam** [comment]
@nalimilan Thanks!
