### ISSUE TITLE
Feature: use an existing list of names for new variables

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/DataFramesMeta.jl#87]
In `DataFrames` you can write the following: 

```
names = [:newName1, :newName2, :newName3]

for name in names 
    df[name] = 5
end
```

I believe that DataFramesMeta's version of this does not make it possible to do such a thing with the `@transform` macro. With `DataFrames`, you can store names as a list of symbols, but there is no equivalent object you can use to store names when you with to use `@transform(x = :oldVar)`command. 

Is this a missing functionality?

**Comment by pdeffebach** [comment]
Or you could use some version of the `^(x)` syntax that is on the RHS of expressions, and expand it so it also works on the LHS of expressions. 

However I should really do more research into `dplyr` to make sure this approach isn't the exact same as what they are doing.

**Comment by davidagold** [comment]
Also, @pdeffebach, I think your second suggestion is much preferable to your first. IMHO, trying to guess what a user intends based on what's defined in the local environment is generally a bad idea.

*recedes back into woodwork*

**Comment by pdeffebach** [comment]
I appreciate that `dplyr` does this, and I understand how to use it more or less, but I am always frustrated with having to remember the syntax that I end up just using `$` in the end, or avoid functional programming at all. 

It seems to be that Julia could be able to do this better. I'm curious if the devs think that adding a `^(x)` syntax is something thats easy to do, because it seems like it just means adding an 
`if head(expr) == ^` somewhere in one of the many helper functions.

**Comment by tshort** [comment]
It's doable. I wouldn't vote for inclusion, though. Seems like a low priority for increased code complexity. Seems like just doing the loop or writing a function to do the operation would be cleaner. That said, one of the other maintainers might want to include it.

**Comment by pdeffebach** [comment]
Fair enough. I could live with using `df[...]` for functions. But it would be nice!

One thing to note is that in `dplyr`, `tibbles` and `data.frames` have slightly different behavior in functions as well, with `tibbles` return dataframes more frequently than `data.frames`. Julia doesn't have this annoyance.

**Comment by davidagold** [comment]
> One thing to note is that in dplyr, tibbles and data.frames have slightly different behavior in functions as well, with tibbles return dataframes more frequently than data.frames. Julia doesn't have this annoyance.

Personally, I try never to return a `data.frame`, but that's just me =p

**Comment by pdeffebach** [comment]
I spent some time on this last night. I think there are two issues that are at play. Two things are impossible to with DataFramesMeta but for different reasons. 

1. Modifying an existing variable with `@transform`. This should be feasible with the `_I_` function. 
```
julia> t = :x3
:x3

julia> @transform(df, _I_(t) = 100)
ERROR: syntax: keyword argument is not a symbol: "_I_(t)"
```

This can probably be resolved by fixing an overly restrictive error message somewhere. 

2. Creating a new variable based on an old name. This will require a new call to the `onearg` function somewhere, probably [here](https://github.com/JuliaStats/DataFramesMeta.jl/blob/5d0b9b13d0755badbc82279a3acf02e99dba7330/src/DataFramesMeta.jl#L631). We need some syntax that goes from 

```
var = y
g(var) -> y #rather than
_I_(var) -> :y
```

**Comment by pdeffebach** [comment]
I think this is more trouble then its worth. 

`@tranform(df, _T_(var) = _I_(xx) + 100)` is both ugly and goes against the rest of Julia's rules for assignment. 

This is a perfectly feasible workflow. `_I_()` is pretty ugly but I understand why its necessary. 

```
 function makedata(df, y, xx)
       df[y] = @with df begin
       _I_(xx) + 100
       end
end
```
