### ISSUE TITLE
@> begin df versus @byrow! df begin 	

### ISSUE THREAD

**Issue by pdeffebach** [JuliaStats/DataFramesMeta.jl#92]
This is a small gripe with `DataFramesMeta`

When using the `linq` macros, you write `df = @> begin df`

When using other `DataFramesMeta` macros, you write the begin first with `df = @byrow! df begin`

Any interest in changing the `linq` macro to be `@> df begin`?

**Comment by ararslan** [comment]
That seems like a good idea to me. What do you think, @tshort?

**Comment by tshort** [comment]
`@linq` is separate from `@>` (that comes from Lazy.jl). So, I'm not sure what you're asking. We can't change `@>` as we don't own it.

**Comment by pdeffebach** [comment]
Ah  i meant `linq` "style" chaining macro `@>`. 

Since it comes from Lazy.jl, i understand its not realistic to change. Oh well, I can live with that.

**Comment by ararslan** [comment]
Sorry for misunderstanding, I didn't realize we took it from Lazy.

**Comment by pdeffebach** [comment]
An update, you can actually use `@>` with the order of other things. 

```
using DataFrames, DataFramesMeta, Lazy

df = DataFrame(rand(10, 10))
df2 = @> df begin 
@transform(y = 10)
end
```

So my annoyance is unmerited.

**Comment by tshort** [comment]
Good to know. Thx.
